aurelia/cli

index.js, lib/logger/index.js
This feature resolves the feature request #11  
Using this simple logger, you can simply require `lib/logger` and use it in one of the three ways. 
```
logger.log('Something') -> [aurelia]: somthing
logger.err('some error') -> [aurelia] [Error]: some error
logger.ok('good to go') -> [aurelia] [Success]: good to go
```
=> feat(logger) Create Simple CLI Logger

commands/index.js
this fixes the way how to find the proper command. First it looks whether a subfolder named like the command is existing, then if a file named like the command and eventually exists with an error message
Fixes issue https://github.com/aurelia/cli/issues/46
=> fix(cmd): fixes the command resolver

lib/installer.js
this fixes the installation procedure of jspm via the Node API.
=> fix(jspm): fixes jspm install process

bin/aurelia.js, package.json, src/index.js
This PR replaces commanderjs with aurelia-command.
I have also modified the `aurelia.init()` and `aurelia.command()` from `src/index.js`
I have also placed `argv` on `process.AURELIA`
=> feat(aurelia-command): Add New Command API for aurelia-commands

gulpfile.js, src/decorators.js, src/index.js
this fixes the babel transpilation inside the gulp script, to include ES7 decorator support
=> fix(build): fix gulp build script

README.md, bin/aurelia.js, gulpfile.js, package.json, src/lib/bundler/index.js, src/lib/bundler/js-bundler.js, src/lib/bundler/template-bundler.js
As of now, we are directly using `systemjs-builder` for bundling js modules. For `systemjs-builder` a module is not just it's name rather it's `name + version`. So, a valid module name would look like: `github:aurelia/templating-binding@0.12.0`. When we create the `aurliafile` configuration for bundling js modules, we specify both (name + version). This creates a maintenance issue. Whenever we update the project dependencies, we potentially invalidate the `aureliafile` as update tend to change the version number.  To solve this issue, we need to specify the configuration without the version number and internally develop a lookup mechanism for resolving correct moduleName with version from `config.js` for `systemjs-builder`.
One detail to remember is that if we find multiple versions where …
=> Specify moduleName without version in aureliafile.

package.json, src/commands/bundle/index.js, src/commands/unbundle.js, src/lib/bundler/index.js, src/lib/bundler/js-bundler.js, src/lib/unbundler.js
Unbundle any current bundle and remove all bundle js injections from `config.js` and `aurelia-view-bundle` `index` html file.
- The command should respect the new [destFile](https://github.com/aurelia/cli#template-bundle-option) setting for `template` bundle.  
- It should also clear the obsolete injections as well.
=> unbundle command

lib/resources/tasks/run.js, package.json
- Added `historyApiFallback()` function to middleware for `serve` task.
Adding the [connect-history-api-fallback](https://github.com/bripkens/connect-history-api-fallback) allows paths added via PushState to be accessed directly when browsing by typing the path into the querystring, e.g. `/contact` and also when BrowserSync reloads the application due to changes.
This makes it a lot more convenient than having to navigate back to the page you were on when your app reloads.
=> enhancement: Connect History API Fallback

lib/resources/tasks/transpile.js
The `project.transpiler.config` was undefined. Changing this to `project.transpiler.options` allowed me to use the babel plugins
=> fix(undefined-property): Use options over config

lib/resources/tasks/transpile.ts
merge the `.d.ts` files with the changed `.ts` files so referenced types transpile properly
NOTE: this introduces a dev dependency on npm package `event-stream`
=> fix(transpile.ts): fix typescript watch transpile

README.md
Github doesn't render well the HTML code. Add line breaks seems to fix the problem
=> doc(readme): fix html markdown rendering

lib/build/bundled-source.js
If a library in an extra bundle (not vendor-bundle) is referenced in the app code, the bundle config/metadata injected in vendor-bundle is missing the moduleIds (being emitted as null). (Which causes the module files not being loaded correctly at run time). This change fixes that.
=> fix(config) : make sure that moduleId is set in config

lib/build/bundle.js
For instance, on a page with this URL /a/b, by default the bundles will be loaded with this URL /a/scripts/bundle.js. If platform.useAbsolutePath is set to true, they will be loaded with /scripts/bundle.js instead.
=> feat(bundle): add an option to use absolute path in requirejs

lib/resources/generators/attribute.js, lib/resources/generators/binding-behavior.js, lib/resources/generators/element.js, lib/resources/generators/generator.js, lib/resources/generators/task.js, lib/resources/generators/value-converter.js, lib/resources/tasks/process-css.js, lib/resources/tasks/process-less.js, lib/resources/tasks/process-markup.js, lib/resources/tasks/process-postcss.js, lib/resources/tasks/process-pug.js, lib/resources/tasks/process-sass.js, lib/resources/tasks/process-stylus.js, lib/resources/tasks/run.js, lib/resources/tasks/test.js, lib/resources/tasks/transpile.js
After creating a new project with the Aurelia Cli, I was looking through the code it generated to see what it does. One thing I noticed that `eslint`, with the rules provided by the Cli itself, was giving some errors and warnings on the generated code.
This PR fixes those errors and warnings.
The codebase contains more `eslint` errors and warnings, but I've intentionally scoped this PR to just the resources for now as that's the only code output to client projects as far as I can tell.
CLA was confirmed by Rob on https://github.com/aurelia/bundler/pull/47#issuecomment-164531862.
=> chore(linting): fix eslint warnings in resources

.eslintrc.json, package.json
This PR adds the default Aurelia `eslint` ruleset to the project. This helps issues like #266 from regressing.
CLA was confirmed by Rob on https://github.com/aurelia/bundler/pull/47#issuecomment-164531862.
=> chore(linting): add default aurelia eslint ruleset

bin/aurelia-cli.js
Finishes #242.
The next logical step from here would be to refactor `lib/cli.js` to reject non-success cases:
- help command should exit with error code
- when `establishProject` fails, that should exit with error code as well
- probably more, I'm not very familiar with the project
```
$ npm run build:prod
> au build --env prod
[....]
npm ERR! Darwin 15.4.0
npm ERR! argv "/Volumes/Custom/Users/kb/.config/fin/bin/node" "/Volumes/Custom/Users/kb/.config/fin/bin/npm" "run" "build:prod"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! project-ui@1.0.0 build:prod: `au build --env prod`
npm ERR! Exit status 1
npm ERR! There is likely additional logging output above.
$ echo $?
1
```
=> feat(cli): add exit error code

README.md, lib/build/bundle.js, lib/build/source-inclusion.js
Fixes: https://github.com/aurelia/cli/issues/238
Address some of the issues mentioned here: https://github.com/aurelia/cli/issues/203  
Allow the `source` option in the bundle config to optionally be an
object with two properties, `include`, and `exclude`. This makes it
easier for patterns to be defined by the user, and allows for a more
consistent approach to creating bundles (similar to the aurelia-bundler)
=> feat(bundle,source-inclusion): allow `exclude` option in bundle source

lib/file-system.js, lib/mkdirp.js
Fixes #241.
It uses a small wrapper around `fs.writeFile` to recursively create the directory it wants to write to when it doesn't exist.
The `filendir` module (and its dependency `mkdirp`) are small, so if you don't want to take an external dependency on them, we could inline them.
CLA was confirmed by Rob on https://github.com/aurelia/bundler/pull/47#issuecomment-164531862.
=> fix(build): create ouput directory when missing

README.md, lib/build/bundler.js
This allows the user to add an object under `build.loader.config` to
pass additional parameters to the loader. For instance if you need to
increase the timeout for requirejs, you can add this object under
`build.loader.config`:
```
{
"waitSeconds": 60
}
```
=> feat(bundler): allow the user to add custom configuration options

lib/build/bundler.js, lib/build/source-inclusion.js
closes https://github.com/aurelia/cli/issues/270
BundledSource's were created for resources in the bundle config, but the BundledSource's were not registered in the bundler ([this](https://github.com/aurelia/cli/blob/master/lib/build/bundler.js#L96) did not happen). So when the tracer begins to trace all the files (including the resources) it would find [here](https://github.com/aurelia/cli/blob/master/lib/build/bundled-source.js#L82) that the file is not in the bundle and it would create another BundledSource.
Then after logging the files array [here](https://github.com/aurelia/cli/blob/master/lib/build/bundle.js#L115) I noticed that there were two files with the same path: `C:\Development\scaffolded\cli-issue-270\node_modules\my-plugin-with-resources\counter.js`. One of those had a …
=> fix(source-inclusion): BundledSource must be registered in the bundler

lib/resources/content/karma.conf.js, lib/resources/content/karma.conf.ts, lib/resources/test/aurelia-karma.js
To do that, we rely on client.args from karma's configuration to
exchange the values between karma and Aurelia. We can then get the
values in aurelia-karma.js with karma.args.
Close #246
=> fix(resources): use paths.root in aurelia-karma.js

lib/build/bundle.js, lib/build/bundler.js, lib/build/index.js, lib/build/loader.js
Resolves:
https://github.com/aurelia/cli/issues/328
Abstracted out the loader config generator from the `bundle.js`.
Exported on the `build` object the function `generateLoaderConfig`
which can be used to create a loader config without writing your
project to files.
BREAKING INTERNAL CHANGE: `bundler.write` now only writes each bundle,
while `bundler.build` will build each bundle and then write them.
=> feat(bundler, bundle): abstract out loader config generator

lib/build/bundle.js, lib/build/dependency-inclusion.js, lib/build/source-inclusion.js
fixes https://github.com/aurelia/cli/issues/368
After these changes, all 20 box view/view-models are added to the bundle:
I believe there is another bug somewhere that prevents materialize from working with the cli, but i'll need to look into that. Will open an issue if I find something
=> fix(dependency-inclusion): wait until all resources are traced before bundling

lib/resources/content/settings.json
Most of the users creating a new Aurelia project would probably not need the default built-in Angular1 auto-complete functionality in the newly created project. 
This will turn it off folder/ project based, instead of for all your code (When adding it to user settings). Which allows you to still open up old Angular1 projects and get auto-complete/ suggestions.
=> feat(autocomplete): disable built-in Angular1 auto-complete/ suggest

lib/resources/tasks/process-less.js, lib/resources/tasks/process-less.ts
Stop breaking the stream when a less file doesn't compile by introducing plumber here as well. Also add better error logging through notify. Fixes #382
=> Fix #382 by catching errors with gulp-plumber

lib/commands/new/project-template.js, lib/dependencies.js
remove unused `aurelia-fetch-client` dependencies that were included by
default.
Resolves: https://github.com/aurelia/cli/issues/389
=> refactor (project-template, dependencies): remove unused deps

lib/commands/new/project-template.js, lib/dependencies.js
Resolves: https://github.com/aurelia/cli/issues/371
Move RequireJS and the Text plugin into the node_modules so that
generated code is separated from library code.
=> refactor(project-template,dependencies): move scripts to node modules

lib/build/bundle.js, lib/build/utils.js, lib/commands/new/project-template.js, lib/project-item.js
Resolves: https://github.com/aurelia/cli/issues/332
Use universal (posix) path separators when creating user side code.
=> fix(file-paths): don't use windows style path separators

lib/build/concat-with-sourcemaps/index.js
Fixes #409 
Only add sourcemaps to the sourcemap list if a sourcemap exists for the file.
Interestingly, this also makes the source mapped `src` folder show up the "correct" place.
Verified that sourcemaps now work in Edge:
=> fix(sourcemaps): stop adding non-existent sourcemaps to sourcemap

lib/commands/new/editors/none.js, lib/commands/new/new-application.json
Adds a new entry to the Editor step in the `new` wizard, called "None of the above".
In the final summary, the option is displayed as "Editor: n/a".
=> Add a "None of the above" choice for the Editor step in the `new` wizard

lib/build/amodro-trace/lib/loader/Loader.js, lib/build/bundled-source.js
This allows aurelia.json specify in the loader config that it wants to wrap a shimmed library in a define. Allows this section of code to be useful https://github.com/aurelia/cli/blob/master/lib/build/amodro-trace/write/defines.js#L41-L55
=> fix(transform): enable wrap shim for shimmed definitions

lib/resources/content/tsconfig.json
The "es2017" value encompasses ES2015 and ES2016 as well as the upcoming ES2017.
=> feat(typescript): set lib to es2017 for upcoming js features

lib/build/bundle.js, lib/build/package-analyzer.js
@EisenbergEffect as you asked for, here is the new PR for https://github.com/aurelia/cli/pull/363.
This time it should be right :-)
Actual description:
>Before, the package-analyzer looked for the node_modules folder in only exactly one path step back
to the source files.
I changed this behaviour to use a node-like lookup which looks for the node_modules folder in
the following manner:
./node_modules, ../node_modules, ../../node_modules, etc.
>And this allows to put the root of the source (project.paths.root) somewhere deeper in a file-structure.
Remark:
>As a quick remark:
>When putting the sources in a deeper structure, one has to set the "build.targets.useAbsolutePath" to true in the aurelia.json, otherwise requirejs tries to load the scripts from a wrong directory (I couldn't track …
=> fix(package-analyzing): allow deeper levels for source root

lib/commands/new/project-template.js, lib/project-item.js
The "new" command configuration has been changed in order to prepend the folder "wwwroot" to both
the output and index properties used during the bundling of an aspnet core project
Closes issue #405
=> fix(project-template): use wwwroot as build target for aspnet core

lib/resources/test/aurelia-karma.js
Shamelessly copied from http://stackoverflow.com/a/40246316 after I bumped into this issue myself.
In my opinion, an new cli project should support this out of the box. This would otherwise get especially confusing with TypeScript as one would need to use a .js extension in the import for a .ts file.
=> chore(test):Add missing .js extensions after normalization

lib/resources/content/editorconfig
`*` and `**.*` are mostly equivalent.
=> Merge patterns in editorconfig

lib/build/bundle.js
Just a copy of the 'prepend' logic to allow appending files to the end of a bundle. Useful for legacy (non-amd) Javascript library plugins which require the global object defined in the 'main' library script to be available when the plugin scripts execute.
=> feat(bundle): add support for 'append' property in bundle config

lib/commands/new/project-template.js, lib/resources/tasks/build.js, lib/resources/tasks/build.ts, lib/resources/tasks/copy-files.js, lib/resources/tasks/copy-files.json, lib/resources/tasks/copy-files.ts, lib/resources/tasks/run.js, lib/resources/tasks/run.ts
This PR resolves the problems found in https://github.com/aurelia/cli/pull/415
**Thomas Darling wrote:**
> @fabioluz @AStoker @EisenbergEffect I have a couple of concerns about this.
> 
> > By default root is the src folder and the output is the scripts folder.
>
> I don't understand why the output is relative to the scripts folder.
> I'd very strongly prefer to have it be relative to the project output folder instead, so I don't have to write ../ when copying files that are not scripts - I think copying non-script files will be a much more common scenario for this, such as in the example above, which actually copies font files.
> 
> I'm also wondering why this task runs as part of the serve task - that's for development only, so this won't work on a build server. From my point of view, …
=> fix(copy-files): copy files when building for production

lib/build/bundle.js
Resolves: https://github.com/aurelia/cli/issues/465
Previously, a file hash would be generated for the config target before
the loader config was added. This would cause cache busting issues
since a vendor bundle would not have any changes, and therefore have an
identical hash as previous, but other bundles would have a different
hash. The browser cached version of the vendor bundle would now
incorrectly point to a wrong file.
By moving the hashing to after the loader config is added, we now catch
the caching issue, and generate a new (correct) hash.
=> fix(bundle): hash filename after loader config added

package.json
Refers to #451 
With esprima declared as a dependency, an `npm link` can be used to test local changes without having to run`npm i esprima` first.
I have added it to the dependencies instead of devDependencies because it is used during runtime, even although an `npm i -g aurelia-cli` seems to magically get it from somewhere and I feel like this is safer then having some sort of 'ghost dependency' going on.
=> feat(local-testing): Added esprima to dependencies

lib/cli-options.js
Related: https://github.com/aurelia/cli/issues/488
When a user has a custom node environment (`NODE_ENV`), issues can
arise where the CLI tries to get an environment file named from the
`NODE_ENV`. This typically results in a file not found exception with
no real clues as to what went wrong.
This fix will notify the user if the `NODE_ENV` is being used, and if
it is a non-standard environment option (dev, stage, prod)
=> feat(cli-options): notify user of non-standard environment

lib/build/bundled-source.js
closes https://github.com/aurelia/cli/issues/408
This bug is mentioned in https://github.com/aurelia/cli/issues/461 but this does not close https://github.com/aurelia/cli/issues/461. I wonder if we can somehow call [gulp-notify](https://github.com/aurelia/cli/blob/master/lib/resources/tasks/transpile.js#L22) from the CLI in cases like this.  
I'd recommend to wait for https://github.com/aurelia/cli/pull/419 to be merged so we can confirm that this bug does not reintroduce itself when traces are cached
=> fix(watch): don't stop watch due to nonexisting files

doc/CHANGELOG.md, lib/commands/new/project-template.js, lib/resources/scripts/configure-bluebird.js
fixes #385 
This fix hit me in a moment of inspiration. Now no more errors for configuring Bluebird after promises have been created! This is a breaking change and will require a bump to `0.25.0`.
=> fix(bluebird): move Bluebird config to prepended file

lib/build/bundle.js
Resolves: https://github.com/aurelia/cli/issues/514
Ensures that the index file is modified (when using revisions) at the
correct time. Previously, it was modified before the hashes were
created, resulting in an index file that was not referencing the
correct file path. Now the index file is modified after the hash is
generated.
=> fix(bundle): write index file modifications after hash generation

lib/resources/src/main.js, lib/resources/src/main.ts
=> fix(bluebird): remove unnecessary Bluebird config in main file

lib/commands/new/project-template.js, lib/resources/tasks/run.js, lib/resources/tasks/run.ts
Add new `baseDir` property in aurelia.json with default value of `'.'`.
Override `baseDir` value to `'./wwwroot'` for ASP.NET Core projects.
Also allows `baseDir` to be configurable via aurelia.json instead of
having to change the hard-code value in run.js/ts.
Fixes #531
=> fix(project-template): set baseDir to '.wwwroot' for ASP.NET Core projects

lib/resources/tasks/test.js, lib/resources/tasks/test.ts
fixes ESLint error: Use path.join() or path.resolve() instead of + to create paths.
=> fix(test): esling reports error that path should never be concated as string

lib/commands/new/project-template.js, lib/resources/generators/component.js, lib/resources/generators/component.json, lib/resources/generators/component.ts
I really think we should have a generator for creating components (view model and views. It's the first thing I started looking for when downloading the CLI. 
I discussed this here: https://github.com/aurelia/cli/issues/547 and was asked to create a PR so here it is :)
To use this feature you will write `au generate component`
* You will then input the name of the component.
* After this you will be asked if you want to add the component to any sub folders (for example your feature folders). 
If you leave it empty you component files will be added to the src folder. If you enter a sub folder (or sub folders) that does not exist they will be created.
=> Added default generator for creating components (view model + view)

lib/build/bundle.js, lib/build/package-analyzer.js, spec/lib/build/package-analyzer.spec.js
fixes https://github.com/aurelia/cli/issues/567
@AStoker i'd like to hear your thoughts on the following. We need the root folder of a package (kept in `description.location` and looks something like `c:/development/my-app/node_modules/my-plugin/`) for two things:
1. to look for (and read) the package.json of the package (which is [used](https://github.com/aurelia/cli/blob/master/lib/build/package-analyzer.js#L48) to determine the loader configuration)
2. to determine [what bundle](https://github.com/aurelia/cli/issues/342#issuecomment-286362197) to put files in. In other words, to prevent files from ending up in `app-bundle.js` when they should have ended up in `vendor-bundle.js` (or other)
Currently the root folder of packages inside the node_modules folder is determined as follows. You …
=> find location of packages outside of node_modules, support packages without package.json

circle.yml, spec/lib/build/package-analyzer.spec.js, spec/lib/file-system.spec.js
should allow circleCI to run the tests correctly
=> chore(circleci): resolve minimatch error and tests running on linux

lib/build/bundle.js, lib/build/bundler.js, lib/build/loader.js, lib/configuration.js, spec/lib/build/bundle.spec.js, spec/lib/configuration.spec.js, spec/mocks/bundler.js
closes https://github.com/aurelia/cli/issues/562
with these changes you can do this to supply options to the uglifier:
```
"options": {
"minify": {
"dev": false,
"default": {
"fromString": true
},
"stage & prod": {
"max-line-len": 100000
} 
},
"sourcemaps": "dev & stage"
},
```
@AStoker what do you think?
=> feat(build): allow minify options to be supplied

lib/resources/content/gitignore
Hey everyone !
`.idea` is editor related and `.DS_STORE` is OS related. Both of those files/folders should be inside [a global gitignore file](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) since they are not related to the project.
`scripts` folder is recreate by the CLI when you bundle your application, there's no need to push compiled file so it's better to remove them by default.
=> chore(gitignore): remove no related project files

lib/build/bundle.js
we don't want the build to crash when a 3rd party dependency has invalid sourcemaps
=> fix(bundle): continue build in case of incorrect sourcemap

lib/build/utils.js
Fixes #639
Makes the capture groups optional for single/double quotes in the source file regular expression.
=> fix(bundle): support quoteless script src attribute

lib/dependencies.json
gulp-sass is dependant on node-sass and the current version (2.3.1) tries to download an old version of node-sass that apparently is not available on GitHub anymore. Changing the gulp-sass version to latest version (3.1.0) solves the problem.
To reproduce the problem just install a new project using Sass as the CSS Pre-processor. You'll see that gulp-sass cannot find node-sass version, thus cannot be installed.
Environment: CLI 0.30.0; NPM 5.0.3; Node 8.1.2; SO Windows 10
=> fix(dependencies): update gulp-sass version

spec/lib/build/package-analyzer.spec.js
Previous test fails when running on non-win32 systems.
=> test: fix a test on path "..\\node_modules" which only works on win32

lib/build/bundle.js, lib/dependencies.json
Keep supporting Uglify v2.
Fix error when using Uglify v3.
Update `lib/dependencies.json` uglify-js version to latest 3.0.19
fixes #636
=> fix(bundle): support both Uglify v3 and v2.

lib/build/bundle.js
To fix https://github.com/aurelia/cli/issues/335
=> Add 'dot' option for Minimatch to allow hidden folders

lib/commands/new/unit-test-runners/karma.js, lib/dependencies.json, lib/resources/content/karma.conf.js, lib/resources/content/karma.conf.ts
add the bundle source maps to karma files configuration and add inline source maps to transpiler options so unit tests also have source maps.
closes aurelia/cli#420
=> feat(sourcemaps): inlcude sourcemaps in karma configuration

lib/dependencies.json
update the karma-chrome-launcher dependency in order to enable usage of ChromeHeadless
=> fix(dependencies): update karma-chrome-launcher

lib/build/dependency-inclusion.js
`Bundle.getBundledModuleIds` was only returning the ids of the traced files in the case of a package dependency. This change modifies `DependencyInclusion` to include the actual package name in the module ids for the dependency.
closes aurelia/cli#676
=> fix(systemjs-bundling): include dependency name in bundle config

lib/build/dependency-inclusion.js, spec/lib/build/bundle.spec.js, spec/lib/build/dependency-inclusion.spec.js, spec/mocks/bundler.js, spec/mocks/project-mock.js
closes https://github.com/aurelia/cli/issues/435#issuecomment-293850306
I need to do some final tests and rebase it on master
=> fix(bundler): don't trace dependencies which have no main file

build/tasks/prepare-release.js, build/tasks/update-dependenciesjs.js
Instead of updating all aurelia libraries on prepare-release, I think we should only update aurelia-cli automatically. We want to prevent that packages get updated on prepare-release that introduce breaking changes.
This change causes only aurelia-cli to be updated in dependencies.json when `gulp prepare-release` is called. The command `gulp update-all-dependenciesjs` updates all packages, that you need to manually run and test.
=> chore(versions): only update aurelia-cli on release

lib/commands/new/buildsystems/webpack/index.js
version: 0.31.2
Trying to create a new project using webpack fails with following error:
```
ERROR [ProjectCreation] Failed to create the project due to an error: Unexpected token )
INFO [ProjectCreation] /home/sayem/.nvm/versions/node/v7.10.1/lib/node_modules/aurelia-cli/lib/commands/new/buildsystems/webpack/index.js:41
).addToContent(
^
SyntaxError: Unexpected token )
```
=> fix(webpack): remove comma from arguments

lib/commands/new/buildsystems/webpack/editors/vscode.js, lib/commands/new/buildsystems/webpack/transpilers/babel.js
closes https://github.com/aurelia/cli/issues/723
=> fix(jsconfig): only create jsconfig for babel+vscode

lib/commands/new/buildsystems/webpack/index.js, lib/dependencies.json
In the generated project, the `npm start` task runs `nps` but the dependencies don't have that package so the task fails.
To be foolproof, the executable should be run from `./node_modules/.bin`, but I haven't changed the task because all the tasks in `package-scripts.js` assume that the users will have `node_modules/.bin` added to their path.
=> fix(npm script): add required dependency to start npm task

lib/importer/services/resource-inclusion.js, spec/lib/importer/services/resource-inclusion.spec.js
Previously `au install` and `au import` were looking for resources (css files currently) from the package root, but this should be the package path (the distribution folder of the package) as anything outside of the dist folder is unreachable
I've updated the tests to reflect this, and this resolves the failing test that was made intentionally
=> fix(importer): search for resources from package dist

lib/build/bundle.js, lib/commands/new/buildsystems/cli/index.js, lib/resources/scripts/configure-bluebird-no-long-stacktraces.js
This implements feature request https://github.com/aurelia/cli/issues/752
I added an extra bluebird config file without long stacktraces and changed the default generated aurelia.json file to selectively pick the right settings depending on the chosen environment
=> feat(bundle): prepend and append now support environment specific dependencies

lib/build/amodro-trace/write/packages.js, lib/build/bundle.js, lib/build/concat-with-sourcemaps/index.js, spec/lib/build/bundle.spec.js
multiple fixes to source maps:
- fixes offset problems caused by:
- prepended scripts;
- duplicate dependency main module;
- remove sourece map file comments;
- add EOL separator for the anonymous module wrapper;
closes aurelia/cli#659, related to aurelia/cli#624
=> feat(source-maps): bundling improvements

lib/build/bundle.js
If a vendor bundle contains source maps, currently those source maps
are created/copied over to the dist folder despite source maps being
disabled in the aurelia options. This fix checks to make sure that
source maps should be enabled before making them.
Example:
[sourcemap-bug-test.zip](https://github.com/aurelia/cli/files/1264081/sourcemap-bug-test.zip)
=> fix(bundle): exclude source-maps when applicable

lib/resources/content/gitignore
Update according to https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore.
=> fix(gitignore): track vscode workspace files

lib/resources/content/tsconfig.template.json
This allows non-relative paths to work. `baseUrl` is already set when you choose webpack and typescript.
=> fix(rjs-ts): add baseUrl to tsconfig

lib/resources/tasks/run.js, lib/resources/tasks/run.json, lib/resources/tasks/run.ts
enable `--open` or `-o` flag as a flag for the `au run` task.
this will open the default browser at the application location.
=> feat(cli-bundler): add --open flag

lib/commands/new/buildsystems/webpack/unit-test-runners/karma.js, lib/dependencies.json
This references https://github.com/aurelia/cli/issues/782
I'm still getting the following error when creating new projects using the cli.
`ERROR in ./test/karma-bundle.js
Module not found: Error: Can't resolve 'jest-matchers' in 'D:\Dev\felix\au-webpack-babel\test'
@ ./test/karma-bundle.js 52:15-39`
=> fix(dependencies): add jest-matchers for karma tests using webpack

lib/commands/install/package-argument-parser.js
packages with names like @aspnet/signalr-client were treated like versioned
=> fix(importer): support scoped packages

lib/resources/test/require.aurelia-karma.js, lib/resources/test/system.aurelia-karma.js
Because it contains import for aurelia-polyfills that essential to execute any of the app files. Or else, it may break with "Reflect.getOwnMetadata is not a function" error.
Especially when the unit test is huge.
The require js files seems to load in parallel and asynchronously. So when there
are so many unit tests, sometimes Karma load other js files first before
the setup.ts file, which make further execution may fail (but
sometimes successful). More unit tests will have higher chance for Karma
to be failed due to setup.ts is loaded/required later.
=> Update Karma to fix intermitten unit test failure

lib/build/bundled-source.js
Now you can inject stubs for modules that are only available at runtime and avoid `File not found or not accessible` console logs via `aurelia.json` or cli task.
Closes #802
=> feat(build): add support for external modules

lib/commands/new/buildsystems/webpack/index.js, lib/commands/new/project-template.js, lib/file-system.js, lib/project-item.js, spec/lib/file-system.spec.js
Set encoding:null on binary file resource.
fs.readFile returns raw buffer.
fs.writeFile ignores our default 'utf8' encoding when
incoming data is a buffer.
Closes #688.
=> fix: fix binary file copy on favicon.ico

lib/importer/strategies/amodro.js
When "main" is missing in package.json, nodejs uses
default main file "index.js", it will complain when
default main file is missing.
This fix supports nodejs module with missing "main"
in package.json. It solves importing issue on nodejs
module "date-fns". #831 is related, that PR solves
tracing issue on "date-fns".
=> fix(importer): support nodejs module default main file "index.js" when "main" is missing in package.json

lib/resources/tasks/process-stylus.js, lib/resources/tasks/process-stylus.ts
fixes: https://github.com/aurelia/cli/issues/829
gulp-stylus is throwing on error
which prevents watch in some way 
https://github.com/gulpjs/gulp/issues/71
I've found that we already use plumber to swallow some errors in transpile task and copied imports and pipe configuretions to process-css for stylus
=> fix(stylus): don't stop watch on error

doc/article/en-US/webpack.md
closes https://github.com/aurelia/hot-module-reload/issues/18
=> doc(webpack): explain flags, platform section

lib/resources/tasks/run-webpack.ts
Running with `devServer.https: true` currently does not work because the property is not copied over. This PR fixes that. See this [SO question](https://stackoverflow.com/questions/49687797/serving-https-in-aurelia-typescript-webpack-dev-setup/49704139#49704139).
=> fix(run-webpack.ts): copy the https property from devServer to opts

README.md
Since gulp 4.0.0 is no longer in alpha/beta and has a normal npm release, it's not necessary anymore to reference the full git url. Changing this to `gulp@^4.0.0` makes the installation a little simpler.
=> docs: simplify setup instructions

lib/resources/tasks/jest.js, lib/resources/tasks/jest.ts
jest.runCli returns a promise. This change updates the usage of jest.runCli to use the promise rather than pass in a callback which never will get executed.
closes #896
=> fix(jest): update usage of jest.runCli

lib/commands/new/new-application.json
Because index 0 is used as a means of classifying an option as being (Default) when you choose custom in the CLI at present, RequireJS is presented in the UI as the default. However, Webpack is now the default. The fix for this is to move Webpack to the top of the list so the code on line 155 `text += ' (Default)';` applies to Webpack.
=> fix(cli): default bundler is webpack, so move to position 1

lib/resources/content/tsconfig.template.json
Change "filesGlob" to "include" so that it works consistently across editors ("filesGlob" is specific to atom).
Remove "exclude" to avoid confusion because those globs are already implicitly excluded. They have no effect.
See https://github.com/aurelia/webpack-plugin/issues/143#issuecomment-381603048
=> fix(tsconfig.template.json): fix incorrect files glob

lib/resources/content/webpack.config.template.js
aurelia/binding#702 this is to avoid v1/v2 duplication due to out-of-date dependencies on 3rd party aurelia plugins.
=> fix: enforce single aurelia-binding in webpack bundle

lib/build/bundle.js, lib/commands/new/project-template.js, lib/dependencies.json, package.json
Terser is the current active fork of uglify-es. This is not only required to support babel targeting es6, but also improve compatibility of any vendor js code which uses "const".
closes #883, #490, supersedes #864
=> feat: use terser to replace uglifyjs for better es6 support

lib/cli-options.js, spec/lib/cli-options.spec.js, spec/lib/cli.spec.js
Check env (either from --env or NODE_ENV) against user defined env files (aurelia_project/environments/*).
Normalize Node.js NODE_ENV convention production/development to prod/dev, but only if user didn't define production.js or development.js.
Stop the process immediately if env file is missing.
closes #912
=> fix: fix environment check (--env or NODE_ENV)

lib/package-managers/npm.js, lib/package-managers/yarn.js
@JeroenVinke quotes are back. Sorry about that.
=> fix: fix regression on npm/yarn path when it has white space

lib/package-managers/npm.js
The try-catch block was accidentally removed during refactoring.
@JeroenVinke @EisenbergEffect please release a patch version.
=> fix: fix regression, panic on missing yarn

doc/article/en-US/cli-bundler/cook-book.md
=> chore(doc): update cookbook on materialize-css as v1.0.0 is released as latest version

lib/build/bundled-source.js, lib/build/bundler.js, lib/build/utils.js, package-lock.json, spec/lib/build/bundled-source.spec.js, spec/lib/build/bundler.spec.js, spec/lib/build/util.spec.js
Additional files like yaml were not processed by any gulp tasks. Previously amodro-trace was able to pull them in directly from file system. This fix mimics the same behaviour.
closes #930
=> fix(bundler): fix a regression on missing yaml file for some users

lib/build/bundle.js
The original code supposed to use fast-minify-mode, but somehow it did not. This fix turns on fast-minify-mode, that disables compress. The resulting minified size is surprisingly almost as small as normal mode, but it only uses a quarter of the time. https://github.com/terser-js/terser#terser-fast-minify-mode
closes #928
=> fix(bundler): bypass a nasty terser compress bug by using fast-minify-mode

lib/resources/tasks/build-webpack.js, lib/resources/tasks/build-webpack.ts
Thanks @oising for the fix. @jods4 recommended using a meaningful tap name.
closes #923
=> fix(webpack): use webpack4 hook that replaced deprecated plugin api

lib/resources/content/webpack.config.template.js
Updating the webpack config to use optimization.splitChunks rather than entry.vendor resolves an issue that appears when jQuery or Bootstrap is added.
When attempting to use jQuery or the jQuery Bootstrap extensions in code, webpack is duplicating jQuery across the app end vendor bundles.
Using optimization.splitChunks allows webpack to workout the dependencies and also reduces the size of the generated bundles by splitting them up.
Fixes this issue: https://github.com/aurelia/cli/issues/958
=> fix(webpack.config.template.js): change webpack config to fix bundle duplication issue

lib/build/amodro-trace/read/es.js, lib/commands/new/buildsystems/cli/transpilers/babel.js, lib/project.js
Since upgraded to babel7, preset-env uses "module":false, we have to explicitly pass "loose":true to additional amd/cjs transform plugin.
=> chore(bundler): use loose mode for amd/cjs transform

lib/build/bundle.js, lib/build/bundled-source.js, lib/commands/generate-skeletons/project-definitions/skeleton-requirejs-esnext-aspnetcore.json, lib/commands/generate-skeletons/project-definitions/skeleton-requirejs-esnext.json, lib/commands/generate-skeletons/project-definitions/skeleton-requirejs-typescript-aspnetcore.json, lib/commands/generate-skeletons/project-definitions/skeleton-requirejs-typescript.json, lib/commands/generate-skeletons/project-definitions/skeleton-systemjs-esnext-aspnetcore.json, lib/commands/generate-skeletons/project-definitions/skeleton-systemjs-esnext.json, lib/commands/generate-skeletons/project-definitions/skeleton-systemjs-typescript-aspnetcore.json, lib/commands/generate-skeletons/project-definitions/skeleton-systemjs-typescript.json, lib/commands/new/buildsystems/cli/index.js, lib/commands/new/buildsystems/cli/json-processors/none.js, lib/commands/new/new-application.json, lib/resources/tasks/build.js, lib/resources/tasks/build.ts, lib/resources/tasks/process-json.js, lib/resources/tasks/process-json.ts, lib/workflow/activities/project-create.js, spec/lib/build/bundle.spec.js, spec/lib/build/bundled-source.spec.js
json files are processed especially without using loader-plugin. It supports three module id forms: "a.json", "text!a.json" (or "a.json!text" for systemjs), "json!a.json" (or "a.json!json" for systemjs).
=> feat(bundler): bundle json files by default for app skeletons of cli bundler

lib/build/bundle.js
Previous sorting algorithm mixed alphabetical order and shim order, it could lead to rock-paper-scissor situation (means it could choose to honour alphabetical order above shim order). The new sorting takes two steps, first it sorts alphabetically, then sorts shims. This ensure we only breaks alphabetical order, not shim order.
fixes #955
=> fix(bundler): fix unstable sorting for shim modules

lib/commands/new/buildsystems/cli/index.js, lib/resources/src/main-webpack.js
In AMD (cli bundler) env, somehow babel polyfill has some trouble, use prepend to bypass AMD. The down side of prepend is that it is 90K in size, bypassed babel preset-env's optimisation.
closes #959
=> feat(esnext): use babel polyfill to enable async/await syntax for esnext projects

lib/resources/content/webpack.config.template.js
Addressing #961, when a symlinked package (i.e. a lerna monorepo) exists in node_modules, the child node_modules are resolved in webpack, creating duplicate module ids like './node_modules/symlinked-package/node_modules/some-dependency/index.js' in addition to './node_modules/some-dependency/index.js'.
=> fix(webpack.config.template.js): webpack resolving child node_modules

bin/aurelia-cli.js, lib/cli.js, package-lock.json, spec/lib/cli.spec.js
Don't try to find local aurelia project when running "au new".
Always use global aurelia-cli to execute "au new".
Log cli version.
closes #977
=> fix: avoid early exist of "au new"

package-lock.json, package.json
Pin readable-stream to v2 which is required by stream-browserify.
This enforces auto-tracer to use readable-stream v2 even when user's app has v3 installed. Auto-tracer always resolves module in cli's node_modules folder, before trying user's app's node_modules folder.
=> fix(bundler): fix stubbing on core Nodejs module "stream"

README.md
Added `Follow on Twitter` badge to the Docs.
> It looks like this: 
[![Twitter](https://img.shields.io/twitter/follow/aureliaeffect.svg?style=social&label=Follow)](https://twitter.com/intent/follow?screen_name=aureliaeffect)
=> Add follow on twitter badge 

lib/build/bundled-source.js, spec/lib/build/bundled-source.spec.js
Fixed a bug when tracing a dep with name spaced plugin like "@au/plugin!./foo.html", it also traces module "@au/plugin".
=> fix(bundler): fix plugin prefix/subfix regex match

lib/commands/new/buildsystems/cli/loaders/alameda.js, lib/commands/new/new-application.json, lib/dependencies.json, lib/resources/test/alameda.aurelia-karma.js
This fixes: #1001 
As alameda and requirejs have the same public api I've just duplicated require loader and require.aurelia-karma.js and adjusted it a bit.
The option was added after requirejs e.g.
1. Webpack
2. RequireJS
3. Alameda
4. SystemJS
As alameda has no internal function `load` we could override, I've used the nameToUrl function which serves the same use case.
I've tested application run and test execution for all loaders with jasmine and one with jest.
Also I could not find a test to extend for this use case and did not add any.
=> feat(loader): Added Alameda AMD loader to cli flow

README.md
Add contributing guidelines section to the docs pointing to `CONTRIBUTING.md` file.
=> Add contributing guidelines to Docs

lib/build/find-deps.js, spec/lib/build/find-deps.spec.js
This PR extends the build tracing to not only bundle deps from `<require>` elements but also from `<import>` elements in preparation for vNext's support for both options.
Partial work related to https://github.com/aurelia/aurelia/issues/116
=> feat(find-deps): add build tracing for import elements

lib/resources/content/webpack.config.template.js
The string {spec,test} is not a valid regex and thus didn't match filenames containing spec or test, as was clearly intended.
This caused coverage reports to include these files.
The new regex now correctly excludes these test files.
=> fix(webpack): correctly exclude spec/test files from coverage report

lib/build/bundle.js, lib/build/bundled-source.js, lib/commands/new/buildsystems/cli/index.js, lib/resources/src/main-cli.js, lib/resources/src/main-cli.template.js
A simple global var "global" is created before load all AMD modules. This is a practical way to support nodejs global var "global". In future we will build on top of dumberjs to properly support nodejs global vars "global", "process", and "Buffer" (the last two are still not supported transparently in aurelia-cli bundler).
core-js uses "var define = ..." everywhere, we need to force cjs wrap before we can switch to dumberjs bundler.
With this fix, `@babel/polyfill` now works as an AMD module.
=> fix(bundler): enable tracing @babel/polyfill

lib/build/bundled-source.js
Previously, rarely, but when user has both systemjs app and requirejs app, the bundler could use a wrong cache.
=> fix(bundler): isolate cache between systemjs and requirejs apps

lib/commands/new/buildsystems/general/unit-test-runners/jest.js, lib/dependencies.json, lib/resources/tasks/jest.js, lib/resources/tasks/jest.ts
Callback always resolved successfully even when test failed
Incorrect data was accessed in result data to determine failure
Closes #1052
=> fix(jest task): Return error when tests fail

lib/resources/tasks/cypress.js, lib/resources/tasks/cypress.ts
Make au cypress --run emit error when a test failed to allow a build process/step to fail.
Closes #1057
=> fix(cypress task): Return error when tests fail

lib/build/amodro-trace/write/replace.js, package-lock.json, spec/lib/build/bundled-source.spec.js
When the UMD file was prepared by browserify, those `require('./a.js')` were matched by a hash map like `{'./a.js':1}`. We cannot clean them up to `require('./a')`, as it will end up with missing entry.
closes #1054
=> fix(bundler): skip deps cleanup (remove .js) for UMD file

lib/build/bundle.js
having bundle name specified with path in aurelia.json
bundler produces a sourcemap comment with path included
which leads to sourcemap not being loaded by browser
=> fix(sourcemaps): strip path from bundle sourcemap

lib/build/amodro-trace/write/defines.js, lib/build/bundle.js
Special treatment for jquery and moment, put them in front of everything else, so that jquery and moment can create global vars as early as possible. This improves compatibility with some legacy jquery plugins.
Note as of momentjs version 2.10.0, momentjs no longer exports global object in AMD module environment. There is special code in lib/build/amodro-trace/write/defines.js to bring up global var "moment".
=> fix(bundler): improve compatibility with legacy libs that depends on jquery or momentjs

lib/workflow/questionnaire.js, skeleton/dotnet-core/package.json__if_webpack
closes #1072
cc @brandonseydel, it might impact your project.
Our release-check task has not turned on tests on `dotnet run`. We need to add that coverage in future.
Tested. @EisenbergEffect it's safe to merge.
=> fix(new-application): add missing dep clean-webpack-plugin to dotnet-core+webpack app

lib/dependencies.json, package-lock.json, skeleton/cli-bundler/aurelia_project/aurelia.json, skeleton/common/package.json, skeleton/plugin/dev-app/main.ext, skeleton/scaffold-minimum/src/main.ext, skeleton/scaffold-navigation/src/main.ext, skeleton/webpack/webpack.config.js
Removed core-js as the import is too late for IE11.
Load promise-polyfill before loading aurelia-bootstrapper. The polyfill can be removed if user don't need to support IE.
closes #1079
=> fix(skeleton): fix Promise polyfill on IE

lib/build/bundled-source.js, lib/build/module-id-processor.js, package-lock.json, spec/lib/build/module-id-processor.spec.js
Define multiple aliases when they can be applied for a path.
Closes #1093
=> fix(CLI-Bundler, Aliases): improve alias support

skeleton/common/.gitignore__append-if-exists
When building npm package, `npm pack` ignored skeleton/common/.gitignore file because it by default ignores any .gitignore file. Rename .gitignore to .gitignore__append-if-exists is the cheapest way to bypass npm's default behaviour. The alternative fix is to use "files" field in package.json, but that's too verbose.
closes #1102
=> fix(skeleton): fix missing .gitignore file in aurelia-cli npm package

package-lock.json, package.json
@EisenbergEffect I noticed the deprecation error on `@babel/polyfill` when install aurelia-cli. This removes `@bably/polyfill` which was not in use since we lifted the nodejs minimum version to v8.9.
=> chore: remove unused @bably/polyfill, not needed for nodejs v8+

skeleton/webpack/aurelia_project/tasks/run.ext
Changed the webpack config so that an aurelia app running with webpack will be exposed from within a container to the host.
Changed "localhost" to "0.0.0.0" : based on what's described [here](https://github.com/webpack/webpack-dev-server/issues/547#issuecomment-284737321)
Also updated the `packge.json` file for the deprecated `opn` [package](https://www.npmjs.com/package/opn) to its new version `open` [package](https://www.npmjs.com/package/open)
=> Run aurelia app with webpack inside a docker container

build/tasks/release-checks/tasks/check-javascript-errors.js, build/tasks/release-checks/tasks/take-screenshot-of-page.js, skeleton/webpack/aurelia_project/tasks/run.ext
Browser in windows has issue to deal with `http://0.0.0.0:8080` ("This site can't be reached"), have to use `http://localhost:8080` in Windows browsers.
@shahabganji this reverts #1122. This is needed because `au run --open` opens browser with the hostname in run task config.
Anyone knows some other way around this Windows edge case?
=> Revert hostname change in webpack

bin/aurelia-cli.js, build/tasks/release-check.js, build/tasks/release-checks/message-history-logger.js, build/tasks/release-checks/suite-runner.js, build/tasks/release-checks/suite-steps.js, build/tasks/release-checks/tasks/install-latest-aurelia-cli.js, build/tasks/release-checks/tasks/install-node-modules.js, build/tasks/release-checks/test-projects-selector.js, build/tasks/release-checks/tests/generic/au-generate.js, build/tasks/update-dependenciesjs.js, lib/cli.js, package-lock.json, package.json, skeleton/cli-bundler/aurelia_project/tasks__if_babel/transpile.js, skeleton/cli-bundler/aurelia_project/tasks__if_typescript/transpile.ts, tsconfig.json
Refactor & update based on PR comments by @3cp 
- Improved build time by keeping skeleton files as-is, they will not be copied to the dist folder.
- Added build step to pretest.
- Lib is now directly transpiled to dist instead of dist/lib
- Bin is no longer transpiled as it only serves as entrypoint
Related to #1067
=> refactor(Build) Don't copy skeleton

package-lock.json, skeleton/webpack/package.json, skeleton/webpack/webpack.config.js
With this fix, `au run --analyze` `au run --hmr` will continue to work.
=> fix(webpack): avoid unnecessary breaking change on argument

skeleton/cypress/README.md, skeleton/cypress/aurelia_project/tasks/cypress.ext, skeleton/cypress/package.json, skeleton/docker/Dockerfile, skeleton/docker/docker-compose.yml, skeleton/protractor/README.md, skeleton/protractor/package.json, skeleton/protractor/protractor.conf.js
@3cp, As we have talked before, I changed the `--run` flag to `--interactive` and made the default behavior of e2e test to offline/non-interactive/headless mode, just like what has been done for `karma`.
Please check out the changes and let me know of any concerns.
=> Change e2e Tests default behavior to headless

skeleton/webpack/webpack.config.js
closes #1152
@graycrow @Sayan751 please review this fix. At mean while, I am going to run through release check on webpack.
=> fix(webpack): fix missing postcss in less/scss/styl processing

skeleton/webpack/aurelia_project/tasks/run.ext, skeleton/webpack/webpack.config.js
Because webpack-dev-server fills up some default value to webpack config. It adds host with value localhost when user didn’t explicitly set in command line. Ref: https://discourse.aurelia.io/t/changing-platform-host-in-aurelia-json-doesnt-change-the-host-ip/3043/10?u=huochunpeng
=> fix(webpack): deal with host option before webpack config

lib/build/bundle.js
closes #1157
@kyttike, @arnederuwe it turns out the postcss sourcemap bug can be fixed in our code, by cleaning up the data we send to concat-with-sourcemaps. The #1157 is not a postcss issue, but manifested as the same source map issue.
=> fix(cli-bundler): avoid passing empty source map to concat-with-sourcemaps

package-lock.json, skeleton/protractor/protractor.conf.js, skeleton/webpack/webpack.config.js
Move promise-polyfill from ProviderPlugin to entry.
Add aurelia-dialog patch for IE11, but user needs to uncomment it.
Closes aurelia/dialog#387
=> refactor(webpack): cleanup promise-polyfill, aurelia-dialog patch for IE11

lib/workflow/questionnaire.js, package-lock.json, skeleton/docker/Dockerfile, skeleton/protractor/protractor.conf.js, skeleton/scaffold-navigation/aurelia_project__if_cli-bundler/aurelia.json, skeleton/scaffold-navigation/package.json, skeleton/scaffold-navigation/src/app.html, skeleton/scaffold-navigation/src/child-router.html, skeleton/scaffold-navigation/src/nav-bar.html, skeleton/scaffold-navigation/src/styles.css__if_not_less_and_not_sass_and_not_stylus, skeleton/scaffold-navigation/src/styles.less__if_less, skeleton/scaffold-navigation/src/styles.scss__if_sass, skeleton/scaffold-navigation/src/styles.styl__if_stylus, skeleton/scaffold-navigation/src/users.html, skeleton/scaffold-navigation/src/welcome.html, skeleton/scaffold-navigation/test__if_protractor/e2e/demo.e2e.ext, skeleton/scaffold-navigation/test__if_protractor/e2e/skeleton.po.ext
This has been a long requested upgrade.
=> feat(scaffold-navigation): upgrade to bootstrap v4 and fontawesome v5

lib/build/bundle.js, spec/lib/build/bundle.spec.js
This PR fixes the issue #1212 related to source paths in source maps files built with Aurelia CLI.
=> Fix issue #1212 - `mapSourceRoot` not calculated correctly on Windows, when `outputDir` outside of project's root folder.
