aurelia/cli

- index.js
- lib/installer.js
- package.json
might be used to install packages directly from github repos. Gets the latest available tag and installs it. Runs NPM and JSPM installs afterwards
> feat(installer): adds a simple github installer

- index.js
- lib/ask.js
- package.json
Create a service for prompting users, and promising answers. 
This feature will make is simpler for us to quickly generate questions, and receive answers, in order to generate necessary code
> feat(ask): Create prompting service

- lib/installer.js
- package.json
- test/installer.spec.js
adds a test setup with jasmine-node and an example test
relates to issue #14
> feat(tests): test setup for the CLI

- index.js
- lib/installer.js
Fixes error handling when getting repository information by checking for null besides undefined. Also defines global variable for index.js, preventing execution
> fix(installer): Fixes installer error handling

- bin/aurelia.js
- commands/bundle.js
- commands/generate.js
- commands/index.js
- commands/init.js
- commands/new.js
- commands/plugin.js
- commands/tb.js
- lib/ask.js
- lib/cli.js
- lib/logger/index.js
- lib/program.js
- lib/spawn-promise.js
> chore(cli): Fix indentation issues in CLI

- bin/aurelia.js
- commands/bundle.js
- commands/generate.js
- commands/index.js
- commands/init.js
- commands/new.js
- commands/plugin.js
- commands/tb.js
- lib/ask.js
- lib/bundler.js
- lib/cli.js
- lib/installer.js
- lib/logger/index.js
- lib/program.js
- lib/spawn-promise.js
fixes wrong indentations and semi-colon placements
fixes https://github.com/aurelia/cli/issues/32
> chore(cli): Fix indentation and semi-colons in CLI

- bin/aurelia.js
- commands/bundle.js
- commands/generate.js
- commands/index.js
- commands/init.js
- commands/new.js
- commands/plugin.js
- commands/tb.js
- lib/ask.js
- lib/bundler.js
- lib/cli.js
- lib/installer.js
- lib/logger/index.js
- lib/program.js
- lib/spawn-promise.js
This closes out indentation issues.
> chore(cli): Fix Indentation and variable declarations

- lib/utils.js
> feat(utils): add utils

- commands/index.js
I created a conflict against PR #41 This is a quick fix, and will revert after merging the PR.
> clean(cmd-index): Fix spacing issues

- commands/generate/generator.js
- commands/generate/index.js
- commands/generate/templates/viewmodel.default.js
- commands/new.js
- lib/installer.js
- lib/program.js
- lib/utils.js
This adds the ability to create a new plugin template and refactors the existing code to provide promises and better logger information
> feat(new): refactored new command to enable plugin setup

- dist/lib/spawn-promise.js
- src/lib/spawn-promise.js
> fix(spawn-promise): Add Promise join for passed arrays

- .gitignore
- .npmignore
- bin/aurelia.js
- dist/cli.js
- dist/commands/init.js
- dist/commands/new.js
- dist/init.js
- dist/lib/config/index.js
- dist/lib/init/index.js
- dist/lib/program.js
- dist/start.js
- gulpfile.js
- src/cli.js
- src/commands/init.js
- src/commands/new.js
- src/init.js
- src/lib/config/index.js
- src/lib/init/index.js
- src/lib/program.js
- src/start.js
Refactored cli, placing everything on env
Create prompts for new command
fix resolves #69 
fix resolves #62
> fix(cmd-new-init)

- gulpfile.js
- package.json
- src/commands/generate/index.js
- src/index.js
- src/lib/generator/index.js
- src/lib/generator/templates/view.default.html
- src/lib/generator/templates/viewmodel.default.js
- src/lib/utils.js
- test/generate.spec.js
This adds the generate command according to the new architecture, as well as some unit tests
> feat(generate): Add generate according to new architecture

- gulpfile.js
- package.json
- src/commands/generate/index.js
- src/lib/utils.js
fixes the help text for the generate command, additionally cleansup utils and fixes gulpfile.
> fix(help): fixes help for generate command

- README.md
- gulpfile.js
- src/commands/generate/index.js
- src/lib/generator/index.js
- src/lib/generator/templates/viewmodel.default.js
- src/lib/utils.js
This fixes a minor bug related to chalk, properly updates the ViewModel template and adds a documentation section to the README
Partially fixes https://github.com/aurelia/cli/issues/83
> fix(generator): fixes generator bug and adds documentation

- package.json
> fix(aurelia-command-version): Update aurelia-command version

- bin/aurelia.js
- package.json
- src/commands/bundle/index.js
- src/commands/generate/index.js
- src/commands/init.js
- src/commands/new/index.js
- src/decorators.js
- src/index.js
This PR includes the followings:
- Fixes the problems of #90 and #98 .
- `generate`, `new`, `bundle`, `init` commands are converted  to new decorator based command interface
- Includes the dynamic command loading for built in commands #88
@PWKad @zewa666  @joelcoxokc please review this.
> Decorated command

- README.md
- src/lib/generator/index.js
- src/lib/generator/templates/viewmodel.default.js
the template will now use one inject decorator and apply multiple targets as attributes
> fix(vm): fixes multiple inject decorators to single

- Aureliafile.sample.js
- package.json
- src/commands/bundle/index.js
- src/lib/bundler.js
@aurelia/cli-team  This PR fixes two bundling issue and improve view bundle injection. Three issues in total. 
I have made commits per issue with the intention of making the review process easier (isolate testing of each issue) for us. If you don't like it let me know, I will squash. 
#102 #103 #104 
Please review.
> Fix/Enhance bundling 

- src/commands/plugin/index.js
- src/lib/installer/index.js
this adds the basic command to install plugins upon asking the user which one to install.
> feat(plugin): add plugin install command

- README.md
an additional readme text for the plugin command
> feat(docs): add readme for plugin command

- src/lib/installer/index.js
fixes the download issue with ghdownload
fixes issue https://github.com/aurelia/cli/issues/155
> fix(download): fixed wrong variable usage

- lib/commands/new/new-application.json
> Fix typo in new-application.json

- lib/resources/generators/task.js
- lib/resources/generators/task.ts
> fix(generators): fix task generator

- lib/resources/generators/value-converter.js
- lib/resources/generators/value-converter.ts
Fix incorrect messsage:
```cmd
>au generate value-converter
What would you like to call the generator?
```
> fix(generators): fix incorrect message in value converter generator

- README.md
Add some notes to help developers see the way import/ require style in cli-generated Aurelia project.
> Improve readme for styling

- ISSUE_TEMPLATE.md
I have changed this one slightly due to the different requirements of the CLI repo. Let me know if updates are needed.
> chore(issue_template): create issue template

- ACKNOWLEDGEMENTS.md
- lib/build/bundle.js
- lib/build/bundler.js
- lib/build/utils.js
- lib/commands/new/project-template.js
resolves: https://github.com/aurelia/cli/issues/205
Allow the user to optionally configure build revisions
> feat(bundler,bundle): allow revision numbers

- lib/build/package-analyzer.js
> fix(package-analyzer): correct resolution of scoped package path

- lib/resources/test/aurelia-karma.js
Based on [this comment](https://github.com/aurelia/cli/issues/259#issuecomment-247174000) by @bootrider 
Close #259
> fix(aurelia-karma): make it compatible with PhantomJS

- lib/resources/tasks/transpile.ts
> fix(transpile): create tsProj every time to avoid crashing

- doc/CHANGELOG.md
> doc(changelog): add aurelia.json upgrade instructions

- doc/CHANGELOG.md
Added required step to npm install requirejs and requirejs/text.
No breaking changes.
> doc(changelog.md): add step to upgrade to 0.23.0

- lib/commands/new/markup-processors/maximum.js
- lib/commands/new/markup-processors/minimum.js
- lib/commands/new/new-application.json
- lib/resources/tasks/process-markup-minify-max.js
- lib/resources/tasks/process-markup-minify-max.ts
- lib/resources/tasks/process-markup-minify-min.js
- lib/resources/tasks/process-markup-minify-min.ts
- lib/workflow/activities/markup-select.js
- lib/workflow/activities/project-create.js
- lib/workflow/workflow-engine.js
Note: All step Ids from `cssProcessor` has been increased by 1
> Add configure template processing step

- lib/cli.js
- lib/commands/alias.json
Resolves: aurelia#412
Add optinal abbreviation for au commands with ./commands/alias.json
> chore(commands): add alias for cli commands

- lib/dependencies.js
- lib/resources/tasks/transpile.ts
Used the example from the gulp-typescript page for ts 2.x
> Changed transpilation task for gulp-ts >= 3

- lib/resources/tasks/run.js
- lib/resources/tasks/run.ts
- lib/resources/tasks/test.js
- lib/resources/tasks/test.ts
closes https://github.com/aurelia/cli/issues/370
> fix(karma): rebuild bundle and tests when source files changes

- lib/file-system.js
- lib/workflow/activities/project-create.js
closes https://github.com/aurelia/cli/issues/460
When there is an existing folder (and without the --here flag):
When using the --here flag in a non-empty folder
> feat(project-create): warn before using existing folder

- lib/build/loader.js
Issue #403 Fix usage of useAbsolutePath with baseUrl
> Fix issue #403 Modify usage of useAbsolutePath with baseUrl

- lib/build/amodro-trace/index.js
- lib/build/amodro-trace/lib/loader/Loader.js
- lib/build/bundled-source.js
- lib/build/bundler.js
This PR is the same as https://github.com/aurelia/cli/pull/419, but squashed and it includes a fix for the mentioned A -> B -> CSS bug. 
cc @huochunpeng
> fix(bundle): cache traces

- lib/file-system.js
- lib/logger.js
closes https://github.com/aurelia/cli/issues/527
> fix(file-system/logger): don't use spread operator to support nodejs 4

- lib/resources/content/tsconfig.json
closes https://github.com/aurelia/cli/issues/234
> fix(typescript): do not build typescript files in aurelia_project folder

- lib/build/bundle.js
- lib/build/bundled-source.js
- lib/build/bundler.js
fixes https://github.com/aurelia/cli/issues/342
> fix(build): ensure that dependencies get in the correct bundle

- lib/importer/services/resource-inclusion.js
- lib/importer/strategies/jspm-section.js
fixes https://github.com/aurelia/cli/issues/558
> fix(importer): search for css files in root dir and resolve import error

- lib/resources/tasks/copy-files.js
- lib/resources/tasks/copy-files.ts
> Fix aurelia/cli#548

- lib/build/utils.js
- lib/resolve/index.js
fixes https://github.com/aurelia/app-ux-showcase/issues/16
> fix(build): enforce strict mode

- spec/lib/project-item.spec.js
- spec/lib/project.spec.js
resolves [circleci](https://circleci.com/gh/aurelia/cli/2) error
> tests(all): use strict

- lib/resources/tasks/test.js
- lib/resources/tasks/test.ts
fixes https://github.com/aurelia/cli/issues/569
> fix(test): resolve join of undefined error

- lib/build/bundle.js
- lib/build/bundled-source.js
- lib/build/bundler.js
- lib/cli.js
closes https://github.com/aurelia/cli/issues/504
> fix(all): improved error reporting

- lib/resources/content/babelrc
- lib/resources/tasks/transpile.ts
fixes https://github.com/aurelia/cli/issues/539
> fix(sourcemap): use src as the sourceroot for sourcemaps

- lib/project-item.js
- lib/project.js
- spec/lib/project-item.spec.js
- spec/lib/project.spec.js
fixes https://github.com/aurelia/cli/issues/596
> fix(generators): create elements/attributes in correct location

- lib/build/bundled-source.js
This makes file not found errors much more easier to read
> chore(bundled-source): improved error logging

- lib/project.js
closes https://github.com/aurelia/cli/issues/605
> fix(project): only transpile aurelia_project in project root

- lib/importer/registry/bootstrap/0.0.0.json
closes https://github.com/aurelia/cli/issues/478
closes https://github.com/aurelia/cli/issues/538
> chore(importer): improve bootstrap import instructions

- README.md
closes https://github.com/aurelia/cli/issues/451
> doc(readme): add instructions to run CLI locally

- lib/resources/tasks/process-markup-minify-max.js
- lib/resources/tasks/process-markup-minify-max.ts
- lib/resources/tasks/process-markup-minify-min.js
- lib/resources/tasks/process-markup-minify-min.ts
…essions
closes https://github.com/aurelia/cli/issues/619
> fix(html-minify): ignore interpolation expressions

- lib/build/package-analyzer.js
- spec/lib/build/package-analyzer.spec.js
…roperty
fixes https://github.com/aurelia/cli/issues/583
> fix(package-analyzer): infer index.js as main

- lib/resources/tasks/process-markup-minify-max.js
- lib/resources/tasks/process-markup-minify-max.ts
- lib/resources/tasks/process-markup-minify-min.js
- lib/resources/tasks/process-markup-minify-min.ts
fixes https://github.com/aurelia/cli/issues/650
> fix(html-minify): resolve parse error of interpolations

- lib/importer/services/resource-inclusion.js
closes https://github.com/aurelia/cli/issues/671
> fix(importer): prevent duplicate dist

- lib/resources/tasks/watch.js
- lib/resources/tasks/watch.ts
closes https://github.com/aurelia/cli/issues/675
> fix(watch): resolve issue where changes are not detected

- lib/build/loader.js
closes https://github.com/aurelia/cli/issues/682
> fix(loader): rev should be applied to bundle for systemjs

- package.json
closes https://github.com/aurelia/cli/issues/667
> fix(deps): update esprima to 4.0.0

- lib/resources/tasks/watch.js
- lib/resources/tasks/watch.ts
closes https://github.com/aurelia/cli/issues/663
> fix(watch): support array of source files

- lib/commands/new/project-template.js
fixes https://github.com/aurelia/cli/issues/734
> fix(webpack): linux case sensitivity

- lib/commands/import/command.js
- lib/commands/install/command.js
closes https://github.com/aurelia/cli/issues/735
> fix(importer): throw clear unsupported error for webpack projects

- lib/commands/new/buildsystems/cli/transpilers/babel.js
- lib/commands/new/buildsystems/cli/transpilers/typescript.js
- lib/resources/tasks/lint.js
- lib/resources/tasks/lint.json
- lib/resources/tasks/lint.ts
adds lint tasks for js and ts using respectively eslint or tslint
> feat(tasks): add lint tasks

- lib/resources/content/webpack.config.template.js
closes https://github.com/aurelia/cli/issues/739
> fix(webpack): uglify by default for production builds

- lib/resources/generators/generator.ts
> fix(generator-ts): use .ts ending in template

- lib/commands/new/buildsystems/webpack/transpilers/typescript.js
closes https://github.com/aurelia/cli/issues/770
> fix(webpack): add tslint config

- lib/build/loader.js
SystemJS configuration is could be usefull for many cases, for example in my case i need to add authorization headers to request done by SystemJS.
> Add option to pass SystemJS configuration

- lib/dependencies.json
closes https://github.com/aurelia/cli/issues/822
> fix(jest): update aurelia-pal-nodejs

- lib/resources/content/launch-cli.json
this adds a default karma debug profile for vscode
> feat(vscode): karma debug profile

- lib/build/bundle.js
allows to incorporate the beauty of
https://github.com/aurelia/cli/pull/635
just reshuffled original commit to not interfere with later additions to master
no checking/testing done
> feat(bundle-report): merge-fix

- lib/commands/new/buildsystems/webpack/index.js
- lib/resources/content/webpack.config.template.js
- lib/resources/tasks/build-webpack.js
- lib/resources/tasks/build-webpack.json
- lib/resources/tasks/build-webpack.ts
- lib/resources/tasks/run-webpack.json
I haven't tested the code as written, I've extracted the necessary configuration from my own webpack build, so please run the necessary tests to make sure I haven't borked everything before merging!
> feat(webpack): add analyze flag to enable webpack bundle analyzer

- doc/article/en-US/aurelia-cli-bundler.md
- doc/article/en-US/basics.md
- doc/article/en-US/gulp-tasks.md
- doc/article/en-US/migrating.md
- doc/article/en-US/recipes.md
- doc/article/en-US/updating.md
- doc/article/en-US/webpack.md
closes https://github.com/aurelia/cli/issues/719
closes https://github.com/aurelia/cli/issues/709
closes https://github.com/aurelia/cli/issues/699
> doc(all): move documentation to CLI repo

- lib/resources/content/webpack.config.template.js
> fix(webpack): remove json loader from webpack config

- lib/resources/content/javascriptservices/webpack.netcore.config.js
> fix(webpack.netcore.config.js): change how plugins are sliced

- lib/build/concat-with-sourcemaps/index.js
Upgrade embedded concat-with-source-maps to latest version.
Close #870
> fix(bundler): fix compatibility with source-map >= v0.6

- lib/commands/new/buildsystems/webpack/index.js
- lib/dependencies.json
- lib/resources/content/webpack.config.template.js
aurelia/binding#702 this is a safe check to warn user about duplicated aurelia-binding v1 and v2 (and potentially other duplicates).
> feat: check duplicated packages in webpack

- lib/cli.js
This fix a regression introduced by https://github.com/aurelia/cli/commit/71893beead16f2ed0bd868b413fadf2131008fb5#diff-f8849ae9f0614ba9464fdd14c2d98dc0
> fix: fix exception on "au new" when running directly in root directory

- lib/resources/content/javascriptservices/Views/Shared/_Layout.cshtml
- lib/resources/content/javascriptservices/Views/Shared/_Layout.cshtml.readme.txt
ref https://github.com/aurelia/templating/pull/647#issuecomment-427989601
> fix: fix html5 syntax

- lib/build/package-analyzer.js
- spec/lib/build/package-analyzer.spec.js
> fix(bundler): be resilient on malformed main/module/browser fields in package.json

- lib/build/dependency-inclusion.js
- lib/file-system.js
- package-lock.json
- spec/lib/build/dependency-inclusion.spec.js
- spec/lib/file-system.spec.js
This fix implemented full algorithm described in https://nodejs.org/dist/latest-v8.x/docs/api/modules.html, after "high-level algorithm in pseudocode of what require.resolve() does".
Came from https://discourse.aurelia.io/t/aurelia-cli-bundler-1-0-0-beta-firebase/1759
> WIP fix(bundler): support nodejs subfolder package.json

- doc/article/en-US/basics.md
Just a few grammatical changes and typo fixes.
> docs(basics): typos and grammatical fixes

- lib/build/bundled-source.js
- lib/build/package-analyzer.js
- lib/build/stub-core-nodejs-module.js
- spec/lib/build/dependency-inclusion.spec.js
- spec/lib/build/package-analyzer.spec.js
- spec/lib/build/source-inclusion.spec.js
Also fix a missed forceCjsWrap on windows. Normalized package description path format.
> test(bundler): cleanup test code on windows

- lib/resources/tasks/build-webpack.js
- lib/resources/tasks/build-webpack.ts
This fixes issue https://github.com/aurelia/cli/issues/956
> fix(webpack): compile hook issue with output

- .travis.yml
@EisenbergEffect @JeroenVinke please turn on travis after merging this.
I guess github will then automatically add travis-ci to PR checklist?
> test: use travis ci to test on multiple OS

- lib/build/bundle.js
- spec/lib/build/bundle.spec.js
> fix(bundler): use topological sort to ensure shim order

- lib/commands/new/buildsystems/cli/transpilers/typescript.js
- lib/commands/new/buildsystems/webpack/transpilers/typescript.js
- lib/dependencies.json
Compiletime error for bluebird fixed by adding typings.
Fixes #991
> fix(cli): add typings for bluebird

- lib/commands/new/new-application.json
- lib/dependencies.json
- lib/resources/content/webpack.config.template.js
- lib/workflow/activities/project-create.js
Improvement of generated webpack config in relation to bundle splitting, long term cachability and other aspects.
Added new question for HTTP protocol to be used in webpack optimisation config
New question only accessible when following the 'custom' path
Choices are HTTP/1.1 or HTTP/2
Default is HTTP/1.1 when the question is not presented.
PR for feature: https://github.com/aurelia/cli/issues/969
> feat(webpack): Improvements in CLI generated Webpack config

- lib/resources/content/gitignore
Add dist, coverage-jest and coverage-karma to gitignore
Resolves #854
> chore(gitignore): add dist and unit test coverage dirs to gitignore

- lib/resources/content/webpack.config.template.js
> fix(webpack): revert #970 to restore default webpack module resolution

- lib/commands/new/new-application.json
- lib/ui-enquirer.js
- lib/ui.js
- lib/workflow/activities/input-multiselect.js
- lib/workflow/activities/input-select.js
- lib/workflow/activities/input-text.js
- lib/workflow/activities/project-create.js
- lib/workflow/activities/project-install.js
- package-lock.json
- package.json
- spec/lib/workflow/input-multiselect.spec.js
- spec/lib/workflow/input-select.spec.js
Add Enquirer as the UI lib responsible for all information gathering from the user.
> feat(ui): add Enquirer as UI lib

- lib/build/bundle.js
> fix(bundler): avoid unnecessary rewrite of index.html

- lib/dependencies.json
Update Cypress from 3.1.5 to 3.2.0
> chore(cypress): update package version

- lib/build/amodro-trace/write/defines.js
- spec/lib/build/bundled-source.spec.js
This fixes tracing npm package "noty".
> fix(bundler): avoid appending alias after comment (sourceMap line).

- skeleton/common/tsconfig.json__if_typescript
- skeleton/plugin/README.md
Thank @kennyfowler and @Stefan for the improvement.
> fix(skeleton): for TS plugin, generate d.ts files, allow import {...} from "resources"

- lib/build/bundle.js
The source path should be relative path, not the absolute disk file path. sourceRoot is removed in final bundle source map.
> fix(bundler): fix sourceMap source file path and sourceRoot

- skeleton/webpack/webpack.config.js
> Implemented SASS extraction into CSS files.

- skeleton/cli-bundler/aurelia_project/tasks/watch.ext
@EisenbergEffect safe to merge. Tested.
> fix(bundler): fix missing json watch

- skeleton/webpack/aurelia_project/tasks/run.ext
I have spent some time before I realized that run script is "overwriting" my dev server configuration :-)
> Keep webpack config for dev server working

- build/tasks/release-check.js
- build/tasks/release-checks/tasks/execute-command.js
- build/tasks/release-checks/tests/generic/au-cypress.js
- build/tasks/release-checks/tests/generic/au-protractor.js
- skeleton/webpack/webpack.config.js
@EisenbergEffect these are the final few tiny fixes for v1 release. The release-check had passed on win10 and macOS with those fixes.
> few small fixes

- lib/dependencies.json
- skeleton/cli-bundler/aurelia_project/tasks__if_babel/transpile.js
- skeleton/cli-bundler/aurelia_project/tasks__if_typescript/transpile.ts
- skeleton/cli-bundler/package.json
- skeleton/webpack/aurelia_project/tasks/environment.ext
> fix(skeleton): fix readonly environment files

- build/tasks/release-checks/tasks/check-javascript-errors.js
- build/tasks/release-checks/tasks/take-screenshot-of-page.js
- build/tasks/release-checks/tests/generic/au-cypress.js
- build/tasks/release-checks/tests/generic/au-protractor.js
- build/tasks/release-checks/tests/generic/dotnet-run.js
- build/tasks/release-checks/tests/requirejs/au-run.js
- build/tasks/release-checks/tests/webpack/au-run.js
@EisenbergEffect can release a patch version after merging this. Passed release-check on win10 and mac.
> Adjust release check

- lib/dependencies.json
- package-lock.json
- package.json
- skeleton/webpack/package.json
@EisenbergEffect it's ready to release.
> fix(webpack): bring in "open" to cli deps to avoid breaking existing webpack apps

- package-lock.json
- skeleton/cli-bundler/aurelia_project/tasks__if_babel/transpile.js
- skeleton/cli-bundler/aurelia_project/tasks__if_typescript/transpile.ts
- skeleton/plugin/aurelia_project/tasks/build-plugin.ext
- skeleton/plugin/package.json
take into account --watch when running build-plugin.
include sourcemaps based on environment configuration
> feat(transpile,build-plugin) add sourcemaps and watch support for plugin development

- skeleton/webpack/README.md
- skeleton/webpack/aurelia_project/tasks/build.ext
- skeleton/webpack/aurelia_project/tasks/build.json
- skeleton/webpack/aurelia_project/tasks/run.ext
- skeleton/webpack/aurelia_project/tasks/run.json
@Sayan751 please help to review this fix.
> fix(webpack): bring back au run --env prod

- skeleton/docker/Dockerfile
Update version of aurelia-cli used inside the `Dockerfile` to `^1.2.0`
> feat(Dockerfile): update aurelia-cli inside docker 

- .eslintrc.json
- lib/build/bundle.js
- lib/build/dependency-inclusion.js
- lib/build/inject-css.js
- lib/build/loader-plugin.js
- lib/build/utils.js
- lib/cli.js
- lib/commands/config/configuration.js
- lib/commands/gulp.js
- lib/commands/help/command.js
- lib/commands/new/command.js
- lib/dependencies.json
- lib/file-system.js
- lib/ui.js
- lib/workflow/pretty-choices.js
- lib/workflow/run-questionnaire.js
- package.json
- skeleton/common/.eslintrc.json__if_babel
- skeleton/common/package.json
- spec/lib/build/bundle.spec.js
- spec/lib/build/bundled-source.spec.js
- spec/lib/build/bundler.spec.js
- spec/lib/build/inject-css.spec.js
- spec/lib/cli-options.spec.ts
- spec/lib/commands/config/util.spec.js
This fixes npm warning on outdated aurelia-tools deps.
> chore(all): replace aurelia-tools eslintrc with standard eslint:recommended

- lib/dependencies.json
Pending release-check on all jest skeletons.
> chore(jest): upgrade aurelia-pal-nodejs to latest 2.0.0

- skeleton/docker/Dockerfile
- skeleton/scaffold-navigation/src/nav-bar.html
fixed a wrong `far` instead of `fa` class used in the navbar component
> fix(scaffold-navigation): fontawesome class and docker issue

- lib/build/bundled-source.js
- lib/build/bundler.js
> fix(cli-bundler): warn user about missed source matcher
